name: build

on:
  push: {}

env:
  GOPATH: /home/runner/work/go

jobs:
  test-after-go-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [
          "1.11.13",
          "1.12.17",
          "1.13.15",
          "1.14.15",
          "1.15.15",
          "1.16.15",
          "1.17.7",
          "1.18.3",
        ]
      fail-fast: true

    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build .
      - name: Test
        run: go test -v ./...
  test-before-go-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [
          "1.6.4",
          "1.7.6",
          "1.8.7",
          "1.9.7",
          "1.10.8",
        ]
      fail-fast: true

    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Setup GOPATH
        run: mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
      - name: Copy
        run: cp -r ./ $GOPATH/src/github.com/$GITHUB_REPOSITORY
      - name: Get
        run: cd $GOPATH/src/github.com/$GITHUB_REPOSITORY && go get .
      - name: Build
        run: cd $GOPATH/src/github.com/$GITHUB_REPOSITORY && go build .
      - name: Test
        run: cd $GOPATH/src/github.com/$GITHUB_REPOSITORY && go test -v ./...
